language: java
dist: xenial
jdk:
  - openjdk8
services:
  - docker
env:
  # latest LTS
  - SONAR_VERSION=6.7.6 SONAR_JAVA_VERSION=5.2.0.13398
  # latest releases
  - SONAR_VERSION=7.5 SONAR_JAVA_VERSION=5.12.1.17771
addons:
  sonarcloud:
    organization: "spotbugs"
    token:
      secure: "TO179WgRUyyT2Yg92FpC1r746GaHDMZ7+rMiBqnXztoj5VWTn8U0+M9edyxQ+cKZtCznC4JoimdjBhne52vauWFuQsoczrxtnN7l4w+yemC799Mm5jEuPKoId1CQZkVc5g4hmmeV4Qg6H5K1or1gnl+MGGZ9tbUYOu2v+G2SyAA="
install:
  - if [ -n "$encrypted_71c23004c23b_key" ]; then openssl aes-256-cbc -K $encrypted_71c23004c23b_key -iv $encrypted_71c23004c23b_iv -in .travis/codesigning.asc.enc -out .travis/codesigning.asc -d; fi
  - if [ -f ".travis/codesigning.asc" ]; then gpg --import .travis/codesigning.asc; fi
script:
  - mvn verify -B -e -V -Dsonar.version=$SONAR_VERSION -Dsonar-java.version=$SONAR_JAVA_VERSION
jobs:
  include:
    - stage: smoke-test
      script:
        - 'mvn package && docker-compose -f src/smoke-test/docker-compose.yml --project-directory . run --rm test-lts'
    - script:
        - 'mvn package && docker-compose -f src/smoke-test/docker-compose.yml --project-directory . run --rm test-latest'
    - stage: analysis
      if: ( type = pull_request and head_repo =~ ^spotbugs/ ) or ( type != pull_request and repo =~ ^spotbugs/ )
      script:
        - mvn org.jacoco:jacoco-maven-plugin:prepare-agent verify sonar:sonar -B -e -V -Dsonar.version=$SONAR_VERSION -Dsonar-java.version=$SONAR_JAVA_VERSION
    - stage: deploy
      if: ( type != pull_request ) AND ( ( branch = release-for-lts ) OR ( tag IS present ) )
      script:
        - mvn deploy -B -P deploy -s .travis/settings.xml
notifications:
  email: false
