on:
  pull_request_target:
    paths:
      - '.github/actions/sonar-update-center/**'
  push:
    branches:
      - master

defaults:
  run:
    working-directory: .github/actions/sonar-update-center

jobs:
  build:
    runs-on: ubuntu-latest
    environment: >
      ${{ (github.event_name != 'pull_request_target' && 'internal') || (
      (github.event.pull_request.author_association == 'OWNER' || 
      github.event.pull_request.author_association == 'COLLABORATOR' || 
      github.event.pull_request.author_association == 'MEMBER') && 
      'internal' || 'external') }}
    steps:
      - name: Decide the ref to check out
        uses: haya14busa/action-cond@v1
        id: condval
        with:
          cond: ${{ github.event_name == 'pull_request_target' }}
          if_true: refs/pull/${{ github.event.pull_request.number }}/merge
          if_false: ${{ github.ref }}
      - uses: actions/checkout@v4
        with:
          ref: ${{ steps.condval.outputs.value }}
      - name: Read .nvmrc
        run: echo "NVMRC=$(cat .nvmrc)" >> $GITHUB_OUTPUT
        id: nvm
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '${{ steps.nvm.outputs.NVMRC }}'
          cache: npm
          cache-dependency-path: .github/actions/sonar-update-center/package-lock.json
      - run: |
          npm ci
          npm run all
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  integration-test:
    runs-on: ubuntu-latest
    steps:
      - name: Decide the ref to check out
        uses: haya14busa/action-cond@v1
        id: condval
        with:
          cond: ${{ github.event_name == 'pull_request_target' }}
          if_true: refs/pull/${{ github.event.pull_request.number }}/merge
          if_false: ${{ github.ref }}
      - uses: actions/checkout@v4
        with:
          ref: ${{ steps.condval.outputs.value }}
      - uses: ./.github/actions/sonar-update-center
        id: integration-test
        with:
          prop-file: findbugs.properties
          description: Use SpotBugs 4.9.3, sb-contrib 7.6.8, and findsecbugs 1.13.0
          minimal-supported-sq-version: 9.9
          latest-supported-sq-version: LATEST
          changelog-url: https://github.com/spotbugs/sonar-findbugs/releases/tag/4.3.0
          download-url: https://repo.maven.apache.org/maven2/com/github/spotbugs/sonar-findbugs-plugin/4.3.0/sonar-findbugs-plugin-4.3.0.jar
          sonar-cloud-url: https://sonarcloud.io/summary/new_code?id=com.github.spotbugs:sonar-findbugs-plugin
          public-version: 4.3.0
          github-token: ${{ secrets.GITHUB_TOKEN }}
          discourse-api-key: ${{ secrets.DISCOURSE_API_KEY }}
          skip-creating-pull-request: true
          skip-announcing: true
      - uses: actions/upload-artifact@v4
        with:
          name: updated-properties-file
          path: ${{ steps.integration-test.outputs.prop-file }}
